name: hdbscan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - hdbscan>=0.8.38
  - numpy>=1.26
  - pandas>=2.0
  - scikit-learn>=1.4
  - matplotlib-base>=3.8
  - seaborn>=0.13
