name: read_clustering
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas =2.3.3
  - matplotlib-base =3.10.7
  - datashader =0.18.2
  - holoviews =1.22.0
  - bokeh =3.8.1
  - scikit-learn =1.7.2
  - hdbscan =0.8.39
  - umap-learn =0.5.9

