name: pacmap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - pacmap>=0.7
  - pandas>=2.0
  - numpy>=1.26
  - matplotlib-base>=3.8
  - seaborn>=0.13
  - scipy>=1.11
